services:
  db:
    build: 
      context: .
    shm_size: 128mb
    container_name: mailer-db
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - ${MAILER_DATABASE_PORT}:5432